# Introduction

```{r load_data, echo=FALSE, cache=TRUE}
load("../output_files/Data_set_1/Waterfall.RData") # to be changed later to load(paste("../",image_analysis))```
```


## Context

Using social media data, FSA wants to be able to track endorcement of allergen based legislations in the UK.
There are two streams of analysis involved in this project :

### Stream 1
Using social media data, we would like to determine whether some Local Authorities face more allergy-relate issues than others by tracking:

- Allergy enquiries: Do consumers experience negative or positive reactions from staff when enquiring about allergen information in restaurants/ food outlets?
- Food labelling: Do consumers face issues with incorrect or incomplete food labelling?
- Reporting reactions: Do consumers report allergic reactions to food or near-misses?

### Stream 2
Based on a list of 14 common allergens provided in the EU legislation, we will focus on these 2 areas:

- How much are each of the 14 allergens being talked about, and are they usually mentioned in isolation or in combination with others? What insight can we gain by analysis of posts relating to these 14 allergens?
- Are other allergens outside of this list of 14 being talked about? We will explore this by: (a) using a list of other likely allergenic foods provided by subject matter experts, and (b) for posts that do not contain any of the main 14, are there any common food themes. Are any of these mentioned more than any of the 14 allergens?


