# Data Analysis

## Supporting local authorities

### Approach

The idea is to use provided data in order to find out information about: 
1. Allergy enquiries
2. Food labelling
3. Reporting reactions

Our approach was to use each of these elements and to find words related to the subject.

Let's take Food labelling as an example. The idea is to find cases where consumers face issues due to incorrect food labelling.

We divided it into the following list:

`c("consumer", "issue", "labelling", "allergy")`

We used a Google library called Word2Vec an efficient implementation of the continuous bag-of-words and skip-gram architectures for computing vector representations of words.

For each of the words consumer, issue, labelling and allergen, we used word2vec to generate dictionaries of words with a strong semantic proximity.

If we talk the word allergy, applying word2vec functions to it provided us with a list of words related to the allergen subject.
With some data cleaning and manual rework, we obtain a dictionary with <key> and values.

Example for allergy :
`
allergy
allergy,allergen,allergenic,allergens,allergic,allergies,allergy,
`

This processed is applied to all the words that we will use to identify issues with food labelling.

We will generate a DFM composed of the list of all the entries (tweets, news, forum) by line, the column will be the key of our dictionary (in that case "allergy")
Because some of these may be repeted several times in a same document tweet or forum posts, the DFM is **normalized** containing 1 for  any occurence of the word >= 1. The matrix is composed of 0 and 1, corresponding to the occurrences of the context words. 


### Labelling

Using the previous generated matrix, we will apply the following logic to filter and label the tweets as per their corresponding context.

Staying in the example of food labelling, we apply the following logical expression : 

[(consurmer AND issue AND labelling) OR (incorrect AND allergy AND labelling) OR (consumer AND allergy AND labelling)]

When one of the above conditions is verified, we flag the corresponding document (tweet, or post forum) with the food_labelling value to 1

The same process is applyied for the allergies inqueries and reactions reports.

## Identifying common allergens

A similar approach is used to identify common allergens. The difference is that we already know the predefined list of keywords we are looking for.

In that case, we built dictionaries for the 14 allergens provided, and for the other list of allergens using the same principal as in first stream.

`
"celery"
c("celery","celery","celeri")
`

`"cereals containing gluten"
c("cereals_contain_gluten","gluten","wheat","rye","barley","barli","oat")
`


```{r, exampleplotchunk, echo=FALSE}

if (knitr:::is_latex_output()) {
  
labelling_reaction <- ggplot(subset(labelled.df, food_labelling > 0 ), aes(x = Week, y = food_labelling, fill = reactions_report))+
  stat_summary(fun.y = sum, # adds up all observations for the month
               geom = "bar") +
  theme_minimal()+
  labs(x="Month", y="Mentions Flagged for Food Labelling", fill="Class of Reported Reaction")+
  theme(legend.position="bottom")+
  scale_x_date(breaks = "month")+
  scale_fill_manual(values = c("grey90","yellow","red"))+
  ggtitle("Food Labelling Over Time by Sentiment Class (All Sources)")+
  facet_grid(sentiment_class~.)+
  theme(axis.text.x = element_text(angle = 45, vjust = 1,
                                   size = 12, hjust = 1))+
  theme(strip.text.y = element_text(angle = 0))+
  theme(panel.grid.minor = element_blank())
labelling_reaction
  
} else {
shinyApp(

  ui = fluidPage(
    selectInput("region", "Region:",
                choices = colnames(WorldPhones)),
    plotOutput("phonePlot")
  ),

  server = function(input, output) {
    output$phonePlot = renderPlot({
      barplot(WorldPhones[,input$region]*1000,
              ylab = "Number of Telephones", xlab = "Year")
    })
  },

  options = list(height = 500)
)
}
```



